### PR TITLE
Added the support of Panorama view mode in AaaG HWC.

### PR DESCRIPTION
**Pull request by shuangwan01**
This feature support combining 1 physical display and 1 SOS display
like one wide resolution display to AOSP framework. HWC be responsible
to feed the part of screen into physical display and SOS accordingly.

Tracked-On: https://jira.devtools.intel.com/browse/OAM-70254
Tests: AaaG be able to split screen and sharing part of it with SOS.
Signed-off-by: Wan Shuang <shuang.wan@intel.com>

### CODE REVIEW

**Comment by shuangwan01** [comment]
> 1. Need Change-Id

Change-Id added.

**Comment by shuangwan01** [comment]
> One large commit review is not generally welcomed
> Why not split your work into smaller commits
> The process make code easier to review and maintain
Understand your point. And submitted them as a whole is due to all changes are all for implementing new feature: Panorama view mode in HWC. To make review more easier, I would like to have short summary for each files and hopefully this could help the reviewers understanding the purpose of the changes easily.
# Changes in below 2 files are for adding new source cpp file: common/display/virtualpanoramadisplay.cpp to HWC share library
common/Android.mk
common/Makefile.sources

# Changes in below file is for parsing Panorama view feature's config options from hwc_display.ini and instantialize the Panorama view mode
common/core/gpudevice.cpp

# Changes in below 2 files are to reuse Mosaic mode for Panorama view feature (screen spliting and feeding part of screen to it's sub-displays) and added the specific logic for Panorama view mode since there is only one physical display attached in AaaG though size of attached displays are 2.
common/core/mosaicdisplay.cpp
common/core/mosaicdisplay.h

# Changes in below 2 files are to move the hyper dmabuf buffer common defintions to a separated file common/display/hyperdmadisplay.h and it will be reused in virtualpanoramadisplay.h
common/display/hyperdmadisplay.h
common/display/virtualdisplay.h

# Below 2 new files are the core part for implementating panroama view feature and majority soure codes are to share part of screen content with SOS via hyper dmabuf. 
common/display/virtualpanoramadisplay.cpp
common/display/virtualpanoramadisplay.h

# Changes in below file are new config options added for panorama view feature.
hwc_display_virt.ini

# Changes in below file are to add the pointer to Panorama view instance
public/gpudevice.h

# Changes in below file are make new class VirtualPanoramaDisplay be friend class of struct HwcLayer
public/hwclayer.h

# Changes in below 3 files are to add interface for instantialize the class VirtualPanoramaDisplay
wsi/displaymanager.h
wsi/drm/drmdisplaymanager.cpp
wsi/drm/drmdisplaymanager.h

**Comment by js0701** [comment]
The major problem is check multiple guest display support

**Comment by shuangwan01** [comment]
> The major problem is check multiple guest display support

The source code is updated to support more than one physical display attached to Panorama view.

**Comment by js0701** [comment]
Please address other comments, separate functions etc

**Comment by js0701** [comment]
@Shao-Feng 
Just found this demo is based on libmingbm
Can you update a README file about how to compile libminigbm
and how to run test case

**Comment by shuangwan01** [comment]
> Please address other comments, separate functions etc
Compiling Panorama view feature according to macro is added and parsing Panorama config options have been moved into separated functions too.

**Comment by js0701** [comment]
@shuangwan01  error checks for this PR failed

**Comment by shuangwan01** [comment]
> @shuangwan01 error checks for this PR failed

Sorry the missed to apply coding style correction for missed files in previous commit. The fix has been submitted.

**Comment by shuangwan01** [comment]
> > @shuangwan01 error checks for this PR failed
> 
> Sorry the missed to apply coding style correction for missed files in previous commit. The fix has been submitted.

looks it's build system issue when running apt-get, I will do little bit revision and trigger the build again.

**Comment by js0701** [comment]
closed as merged

**Pull request closed without merging**
