### PR TITLE
QueueUpdate refractory: add separate function for overlay layer initi…

### PR DESCRIPTION
**Pull request by js0701**
…alize

This help to reduce the lines of QueueUpdate functions

Jira: None
Tests: Compilation and HWC works normal in Android
Signed-off-by: Lin Johnson <johnson.lin@intel.com>

### CODE REVIEW

**Comment by js0701** [comment]
@csravelar 
do you know why travis is failing again?

**Comment by strassek** [comment]
I agree that QueueUpdate is far too long but I'm not sure if I'm sold on breaking this code out into its own function. Couldn't we get the same readability improvement by placing some comments around the initialization sequence?

**Comment by js0701** [comment]
@strassek we have serveral functions with a few hundred lines of code.
This is not aligned with any software methodology and tend to be buggy
Break them into smaller functions not only make them readable, but aslo more robust

**Comment by js0701** [comment]
@kalyankondapally  Also removed unecessary gpu_fd_ caused by my last commit. Thanks

**Comment by harishkrupo** [comment]
@js0701 Could you please rebase your patch?

**Comment by js0701** [comment]
@harishkrupo rebase done

**Comment by js0701** [comment]
Closed as merged

**Pull request closed without merging**
