### PR TITLE
Add doxygen config and document some of the public APIs

### PR DESCRIPTION
**Pull request by strassek**
The APIs defined in the public headers represent the boundary between core
IA-Hardware-Composer and the platform specific implementations. Start adding
documentation to help specify the expected API behaviors.

Jira: GSE-1575
Test: doxygen Doxyfile
Test: firefox html/index.html

Signed-off-by: Kevin Strasser <kevin.strasser@intel.com>

### CODE REVIEW

**Comment by csravelar** [comment]
In the doxygen config, some things that might also be worth taking a look at are setting Include_file_patterns, exclude, and source_browser. Also a good thing to discuss is if we plan to only locally host the generated html and latex in an output directory or if we also plan to host it live anywhere as official documentation for the project. Good work on this patch and thank you for the much needed documentation

**Comment by strassek** [comment]
@csravelar I'm explicitly including the documented headers with 'INPUT' -- I didn't see any value in including undocumented files in the Doxygen output. I haven't looked at SOURCE_BROWSER or live hosting, I think both of those things are outside of the scope of this patch.

**Comment by csravelar** [comment]
Ah alright, was just interested in finding out if there was any future plans for those

**Comment by harishkrupo** [comment]
@strassek Please rebase on top of master, travis issues are now fixed.

**Comment by kalyankondapally** [comment]
good to be merged ?

**Comment by strassek** [comment]
@kalyankondapally your call, no one has rejected the patch or requested any changes

**Comment by js0701** [comment]
closed as merged

**Pull request closed without merging**
