### PR TITLE
Use SurfaceFlinger to do client composite if layers more than 3

### PR DESCRIPTION
**Pull request by dyang23**
If layers more than 3, layer1 and layer2 set to Device composite
type, and other layers set to Client composite type.

Change-Id: I6c32a5d5b3cdd31feb113288fba4afc11842b9b5
Tracked-On:
Signed-off-by: Yang, Dong <dong.yang@intel.com>

### CODE REVIEW

**Comment by js0701** [comment]
Do we consider video need to be a separated plane, that is not client type here?

**Comment by js0701** [comment]
Thanks for this patch
I generally agree with it.
Beyond the comment, just a few things
1) Explain what is the benefit to return client type 
    say, junky frame rate how much reduce
2) Also you can explain the video layer logic, that is we wish to choose original way when we meet video, the HWC will try to separate planes or use VPP for video
3) Add a switch to choose the old way, it will help us to do debug and analysis

**Comment by dyang23** [comment]
If any video layer included, we will keep original logic, that is all the layer will set it as DEVICE type, and how to mapping to plane will handled in present() process.

**Comment by dyang23** [comment]
patch update, please review again.

**Comment by js0701** [comment]
@dyang23 
OK. I will approve. But it just has a not necessary commit? I guess you just need one commit

**Comment by dyang23** [comment]
@js0701 Yes, the not used commit already removed, please review again, thanks.

**Pull request merged**
