### PR TITLE
Fixed one display hang when plug 3 displays in clone mode.

### PR DESCRIPTION
**Pull request by shuangwan01**
JIRA: #1242
Test: Boot into Android home screen.

### CODE REVIEW

**Comment by kalyankondapally** [comment]
merged thanks

**Comment by kalyankondapally** [comment]
causes regression with virtual environment. Can you work with yugang to check why.

**Comment by yugang** [comment]
i tried again, manually add the patch to latest master, and can't reproduce the reg again, not sure why, anyway i will work with shuang to confirm this soon later

**Comment by shuangwan01** [comment]
I will have a try to see if we could reproduce the issue on master in virtual environment and share the update latterly.

**Comment by shuangwan01** [comment]
Just tried the patch on top of HWC master and using master branch of virtual environment. The hang issue is not reproduced. 
Here are some details of testing conducted:
1. HWC master + master branch of virtual environment: reproduced 3 times of third display hang over 15 times of boot up testing and no system boot up issue found;
2. HWC master **+ this patch** + master branch of virtual environment: didn't reproduce third display hang over 15 times of boot up testing and system boot up issue is not found as well.

Based on the test result, the risk of  bring regression is low per evaluation.

@kalyankondapally Could you help to merge the patch?

**Comment by kalyankondapally** [comment]
merged

**Pull request closed without merging**
