### PR TITLE
Fix the memory leak in virtualdisplay.cpp

### PR DESCRIPTION
**Pull request by yhe39**
Jira: OAM-67797
Tests: play vidoe and UI doesn't hang or reboot.

### CODE REVIEW

**Comment by js0701** [comment]
@yhe39 
Please add commit message
Why we need this patch

**Comment by js0701** [comment]
When use git commit, please remember to add -s
that is signed your name to this patch

**Comment by yhe39** [comment]
@js0701 thanks a lot!
@js0701 @jennycao  @yugang please help to check again. Thanks!

**Comment by stripes416** [comment]
@yhe39 We have some wiki pages ([Contributions](https://github.com/intel/IA-Hardware-Composer/wiki/Contributions) and [Conformance](https://github.com/intel/IA-Hardware-Composer/wiki/Conformance)) that have a lot of information on how to contribute to the project (just for future reference if you need it!)

**Comment by js0701** [comment]
merged and commit message corrected

**Pull request closed without merging**
