### PR TITLE
Pass VTS for setBrightness API

### PR DESCRIPTION
**Pull request by yuanzhel**
Tracked-On: OAM-96695
Signed-Off-By: Liu, Yuanzhe <yuanzhe.liu@intel.com>

### CODE REVIEW

**Review by YuanjunHuang — COMMENTED** [review]
@yuanzhel  pls. modify the commit message/title to describe what is changed and what it is for.

**Comment by yuanzhel** [comment]
> @yuanzhel pls. modify the commit message/title to describe what is changed and what it is for.

Done. Please kindly give me +2 review for further merge.

**Comment by Shao-Feng** [comment]
If it is related with capability, should we checking the capability list before returning Unsupported?

**Review by YuanjunHuang — APPROVED** [review]

**Comment by YuanjunHuang** [comment]
> If it is related with capability, should we checking the capability list before returning Unsupported?

HP is requesting for this fix urgently. Suggest merge it first.
Yes agree we shall add real implementation later.

**Comment by yuanzhel** [comment]
> If it is related with capability, should we checking the capability list before returning Unsupported?

Seems now our getCapability never return display::brightness cap, but if it does further, guess this unsupport return will cause VTS failure again.

**Pull request merged**
