### PR TITLE
 MosaicMode: return more reliable fences

### PR DESCRIPTION
**Pull request by harishkrupo**

### CODE REVIEW

**Comment by harishkrupo** [comment]
still need to make changes for weston, so for this PR, travis will fail, for now

**Comment by harishkrupo** [comment]
@kalyankondapally Please merge this: https://github.com/intel/external-weston/pull/1. without it, travis will fail.

**Comment by harishkrupo** [comment]
@kalyankondapally ready to be merged :)

**Comment by kalyankondapally** [comment]
jira:, tests: are missing in u commit message. Can you fix that @harishkrupo  ping

**Comment by kalyankondapally** [comment]
merged

**Pull request closed without merging**
