### PR TITLE
Refactory code: commit_planes can be avoided

### PR DESCRIPTION
**Pull request by js0701**
DisplayPlaneStateList already hold that.
Reduce double vectors can avoid logic complexity

Change-Id: Id8704b6aa8d925ce76708d51dd155fba17decb17
Tests: Android UI normal
Tracked-On: None
Signed-off-by: Lin Johnson <johnson.lin@intel.com>

### CODE REVIEW

**Comment by js0701** [comment]
@shuangwan01 
Can you test if video black stripe issue is here?
@Shao-Feng @shuangwan01 @yhe39 
Let's remove ugly code in this branch.
This is is a beginning

**Comment by shuangwan01** [comment]
@js0701, just tried this patch in local dev environment, the black stripe issue is not reproduced.

**Comment by YuanjunHuang** [comment]
nice change

**Comment by shuangwan01** [comment]
Reviewed the changes, LGTM :-)

**Comment by Shao-Feng** [comment]
LGTM too. merged

**Pull request merged**
