### PR TITLE
Android: Fix unused parameters complie warnings in Makefile

### PR DESCRIPTION
**Pull request by yhe39**
This reduce the unused parameter warning.
Keep these unused parameters for further feature or function.
Just add flag to makefile to deduce these warnings.

Jira: None
Signed-off-by: HeYue <yue.he@intel.com>

### CODE REVIEW

**Comment by yhe39** [comment]
@js0701 @jennycao @yugang ,please help to review. Thanks!

**Comment by js0701** [comment]
@yhe39  Please merge 2 commits into one

**Comment by yhe39** [comment]
@js0701 thanks for your advise, has modified accordingly, please help to check. Thanks!

**Comment by yhe39** [comment]
hi @js0701 , thanks for advise, please check. Thanks!

**Comment by stripes416** [comment]
@yhe39 Please add the info from the top comment in your PR to your commit message in the detailed description portion. https://github.com/intel/IA-Hardware-Composer/wiki/Conformance#commit-messages

**Comment by yhe39** [comment]
@stripes416 thanks! modified accordingly.

**Comment by js0701** [comment]
closed as merged

**Pull request closed without merging**
