### PR TITLE
check_patch.py: Update link address

### PR DESCRIPTION
**Pull request by stripes416**
Wiki reference link was out of date due to wiki update.

Jira: None
Tests: None -- comment change
Signed-off-by: Kelly Ledford <kelly.ledford@intel.com>

### CODE REVIEW

**Comment by stripes416** [comment]
My commit message didn't meet our specs (missing Jira & Test lines) --- I'll change and update.

**Comment by stripes416** [comment]
@harishkrupo Thanks for the review!

I got a celadon build bot message this morning saying my commit message didn't meet specs, so I updated and it dismissed your review.

https://buildbot.sh.intel.com/absp/builders/celadon-autobuild/builds/11/steps/CheckBug/logs/stdio

**Comment by stripes416** [comment]
@harishkrupo It complained at me again and I was wondering why in the world it was --- thanks for the explanation! @js0701 @harishkrupo @MicheleL-Intel  --- what do you think? Should we require commit messages to include:
 'Change-Id: ####
  Tracked-On: jira #'
in order to pass celadon autobuild tests?

**Comment by harishkrupo** [comment]
Two questions:
- Why do we need change-Id? We could have it as it wouldn't affect anything other than occupying some memory.
- Tracked-On: Which link should we provide here? Typically we would need something which is open source and available to all.

**Comment by stripes416** [comment]
In response to your questions @harishkrupo :

* I'm not sure where you even get the change ids. Do they add any context or helpful information?

* True -- Jira isn't  a great documentation source if we are open source. At this point, we've mostly switched from github issues  to jira issues -- most PRs don't have an associated github issue -- but we could document the ones that do here and leave it blank (or say none) otherwise.

The commit message requirement for our project is:
```
Subject -- a title for the patch (<50 characters)

Detailed description

Jira: (link to JIRA issue) and or Github: (#)
Test: (what tests are expected to pass)
Signed-off-by: (Author name & author email address)
```
Would adding "Change-Id:" and "Tracked-On" add any value to our commit messages other then keeping the celadon-buildbot from annoying us?

**Comment by harishkrupo** [comment]
In that case, we could rename Jira to Tracked-On to satisfy the bot.
Change-Id's are automatically generated because of the git-hooks which get cloned in the internal tree.
They are useful for identifying a gerrit's CL. I haven't seen them being used outside gerrit.

**Comment by stripes416** [comment]
@harishkrupo I agree -- lets change 'Jira:' to 'Tracked-On:'

Based on the error log ([here](https://buildbot.sh.intel.com/absp/builders/celadon-autobuild/builds/11/steps/CheckBug/logs/stdio)) it looks like we can still include 'Tests:' but just after the 'Signed-off-by:'

`        However, you need to keep the 'Tracked-On', 'Change-Id',
        'Signed-off-by', ..., fields in the **lastest** paragraph of
        the commit message.`

If we are going to change to 'Tracked-On:' we might as well add the 'Change-Id:' and go the whole mile. I'll send out an email and update the wiki.

**Comment by stripes416** [comment]
Rebased onto current master, which dismissed approving review. Will close as merged as soon as Travis testing is complete.

**Comment by stripes416** [comment]
closed as merged.

**Pull request merged**
