### PR TITLE
Add new hwcservice api and test to query if render target compression is enabled

### PR DESCRIPTION
**Pull request by YuanjunHuang**
hwcservice: Add new api and test to query if render target compression is enabled.

Signed-off-by: Yuanjun Huang <yuanjun.huang@intel.com>

### CODE REVIEW

**Comment by YuanjunHuang** [comment]
@js0701 PTAL

**Comment by YuanjunHuang** [comment]
This is for RBC feature test case.

**Comment by js0701** [comment]
Why we need this feature, who will use it?

**Comment by YuanjunHuang** [comment]
it is for https://jira01.devtools.intel.com/browse/OAM-65434

**Pull request closed without merging**
