### PR TITLE
GPU device use singleton

### PR DESCRIPTION
**Pull request by yhe39**
Simple the HWC code.

Change-Id: I389dea4f7a1770019fb87bd317e57ee4de249024
Tracked-On: https://jira.devtools.intel.com/browse/OAM-72553
Tests: Compile success, system without any issue.
Signed-off-by: HeYue <yue.he@intel.com>

### CODE REVIEW

**Comment by js0701** [comment]
Please update with more information int the commit message

**Comment by js0701** [comment]
The implementation is not thread safe
please use C++11 thread safe singleton
https://stackoverflow.com/questions/2576022/efficient-thread-safe-singleton-in-c
Here is some discussion

**Comment by yhe39** [comment]
@js0701 , please help to review. 
Please let me know if anything. Thanks!

**Comment by yhe39** [comment]
@js0701 modify according to your comment. please help to review. thanks!

**Comment by js0701** [comment]
Closed as merged

**Pull request closed without merging**
