### PR TITLE
do not merge

### PR DESCRIPTION
**Pull request by johnarizona**
don't merge this patch.  it's a dummy patch to reproduce the intermittent travis CI issue and to verify potential fixes.

### CODE REVIEW

**Comment by stripes416** [comment]
@johnarizona It looks like the 'disable hotplug' build for both this pr & #434 both fail at the same place. Both are missing 'gbm'. I'll be looking into this more in the morning.

**Comment by stripes416** [comment]
It looks like it is actually mesa that is failing to build. Here's the log where that happens:

`
make[6]: Entering directory `/home/travis/build/intel/IA-Hardware-Composer/mesa-18.1.5/src/mesa/drivers/dri'
  CXXLD    mesa_dri_drivers.la
../../.libs/libmesa.a(blit.o): error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status
make[6]: *** [mesa_dri_drivers.la] Error 1
make[6]: Leaving directory `/home/travis/build/intel/IA-Hardware-Composer/mesa-18.1.5/src/mesa/drivers/dri'
make[5]: *** [install-recursive] Error 1
make[5]: Leaving directory `/home/travis/build/intel/IA-Hardware-Composer/mesa-18.1.5/src/mesa/drivers/dri'
make[4]: *** [install-recursive] Error 1
make[4]: Leaving directory `/home/travis/build/intel/IA-Hardware-Composer/mesa-18.1.5/src/mesa'
make[3]: *** [install] Error 2
make[3]: Leaving directory `/home/travis/build/intel/IA-Hardware-Composer/mesa-18.1.5/src/mesa'
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory `/home/travis/build/intel/IA-Hardware-Composer/mesa-18.1.5/src'
make[1]: *** [install] Error 2
make[1]: Leaving directory `/home/travis/build/intel/IA-Hardware-Composer/mesa-18.1.5/src'
make: *** [install-recursive] Error 1
--2018-08-23 23:47:45--  http://www.freedesktop.org/software/vaapi/releases/libva/libva-1.7.0.tar.bz2
Resolving www.freedesktop.org (www.freedesktop.org)... 131.252.210.176, 2610:10:20:722:a800:ff:feda:470f
Connecting to www.freedesktop.org (www.freedesktop.org)|131.252.210.176|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.freedesktop.org/software/vaapi/releases/libva/libva-1.7.0.tar.bz2 [following]
--2018-08-23 23:47:45--  https://www.freedesktop.org/software/vaapi/releases/libva/libva-1.7.0.tar.bz2
Connecting to www.freedesktop.org (www.freedesktop.org)|131.252.210.176|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 788519 (770K) [application/x-bzip2]
Saving to: â€˜libva-1.7.0.tar.bz2â€™
`

**Comment by johnarizona** [comment]
I diffed the passing log vs. failing log and the main difference I saw before the build was:
passing:
export LABEL="Default"
failing:
export LABEL="Disable hotplug"
export HWC_FLAGS="--disable-hotplug-support"

I couldn't tell how that would impact mesa to build differently.  One possibility is it causes some minor difference to a component mesa depends on or mesa itself, but gcc is not aware of it so it reuses files that it shouldn't between builds.  According to https://docs.travis-ci.com/user/reference/trusty/
"When specifying sudo: required, Travis CI runs each build in an isolated Google Compute Engine virtual machine that offer a vanilla build environment for every build.

This has the advantage that no state persists between builds, offering a clean slate and making sure that your tests run in an environment built from scratch."

That seems to imply travis may reuse states between builds.  One experiment that may be worth trying is setting sudo: required and see if the behavior changes.

**Comment by johnarizona** [comment]
verified passing after #444 is merged. will close.

**Pull request closed without merging**
