### PR TITLE
Refine VA hsbc module.

### PR DESCRIPTION
**Pull request by feiwan1**
1. Ensure HSBC filter can be created from 1st frame by using
default color value. Otherwise there will be green screen.
2. Integrate Hue/Satation/Brightness/Contrast into one filter.
3. Do memset before set parameters into libva.

Jira: None.
Test: Set/Restore color works as expected.

Signed-off-by: Wang,Fei <fei.w.wang@intel.com>

### CODE REVIEW

**Comment by kalyankondapally** [comment]
For some reason full screen video gets hung with this change on Android IA. I am going to do bit more testing, if you want to check in mean time though.

**Comment by kalyankondapally** [comment]
seems like a false alarm, pls ignore

**Comment by feiwan1** [comment]
Add another path for CSC scaling mode setting in varender.

**Comment by feiwan1** [comment]
Synced with Guanxin, if create HSBC with all 4 default value maybe will have an influence on performance. So I will repush a patch to use only 1 default to create HSBC filter if the filter.size is 0.

**Pull request closed without merging**
