### PR TITLE
Reformat files with clang-format

### PR DESCRIPTION
**Pull request by csravelar**
This patch is the last in a series to get all cpp/h files across
the hwc project to adhear to the clang formatting standards.
This patch focuses specifically on the os directory.

Jira: None
Test: HWC build passes without errors
Signed-off-by: Richard Avelar richard.avelar@intel.com

### CODE REVIEW

**Comment by kalyankondapally** [comment]
thx, I am wondering if it's possible to add a hook in travis to check this for all PR and fail if indentation is not correct. Is this something u can study @csravelar ?

**Comment by harishkrupo** [comment]
I guess this can be done by checking if this has something to return:
`git show origin/master..@ | clang-format-diff.py  -p1 -style=file`.

**Comment by kalyankondapally** [comment]
@harishkrupo Can u send a PR for this change ?

**Comment by csravelar** [comment]
Agreed Kalyan. I was just walking about this with Kelly today. I was wondering if it would be a good idea to just integrate clang along with other static analysis tools like cppcheck that travisCI can run at the beginning to enforce basic things before being allowed pass for peer review. Let me know if there is still interest to do this after harishkrupo's suggestion/PR

**Comment by kalyankondapally** [comment]
@csravelar You should add cppcheck, while harish is looking at the indentation piece of it.

Merged.

**Comment by kalyankondapally** [comment]
@csravelar this might be interesting to add cppcheck and clang static analyzer https://legalizeadulthood.wordpress.com/2014/12/07/adding-static-analysis-to-your-c-github-repository/

**Pull request closed without merging**
