### PR TITLE
Force Vpp composition when video count more than plane count

### PR DESCRIPTION
**Pull request by js0701**
This scenario is true when ACRN only assign 1 plane to Andriod
Then VPP should be used for composition due to 2 reasons
1: If video is protected, 3D patch can't not deal with it
2: Some video effect still wanted on the video layer

Change-Id: I892fef1f13cd4e2b7665b2d5edb7c0203faf118a
Tracked-On: None
Tests: Android UI normal
Signed-off-by: Lin Johnson <johnson.lin@intel.com>

### CODE REVIEW

**Comment by js0701** [comment]
Do not merge

**Comment by js0701** [comment]
@harishkrupo 
This may be related with you PR https://github.com/intel/IA-Hardware-Composer/pull/467

**Comment by js0701** [comment]
@Shao-Feng 
We may need to integrate this PR and @harishkrupo 's PR 467 to enable VPP composition for multiple layers.

**Comment by harishkrupo** [comment]
@js0701 @Shao-Feng 
Yes you will require patches from #467, specifically https://github.com/intel/IA-Hardware-Composer/pull/467/commits/aa03dd727ebf2810d364877aa3d180c3435a7845.
Looks like your patch handles the decision making, so you might require something similar to this for state changes: https://github.com/intel/IA-Hardware-Composer/pull/467/commits/60e6009332605ebd48ef88f3234baa313e6656ab

**Comment by harishkrupo** [comment]
> @harishkrupo I rebased and use your commit in PR467 in here
> We will push after debug and validations

Sure. Thanks :)

**Comment by js0701** [comment]
@Shao-Feng  @harishkrupo 
Please review 
If no problem, please approve. THX

**Pull request merged**
