### PR TITLE
[DONOTMERGE]Revert "An API for dropping DrmMaster and ignoring DRM co…

### PR DESCRIPTION
**Pull request by jennycao**
…mmit"

This reverts commit 5f8d6d27e2b5f89e091b6c93ac2fd35bf0235c83.

### CODE REVIEW

**Comment by js0701** [comment]
If it is a bug we can just fix it instead of revert
@Shao-Feng  @jennycao

**Comment by Shao-Feng** [comment]
It is a bug in security. https://jira.devtools.intel.com/browse/OAM-76929
I will ping Zhenlong for fixing it

**Comment by jennycao** [comment]
this revert patch do not need to merge, if we have quick fix for it.

**Comment by jennycao** [comment]
I revert  patch in release candidate EB https://buildbot.sh.intel.com/absp/builders/f_celadon_opensourcegfx_master-engineering/builds/19 
to continue the pre-integration test.
we will skip this patch to merge to celadon for this round(ww11) if the fix can not catch the release date.

**Comment by Shao-Feng** [comment]
The original commit is removed. Close this one

**Pull request closed without merging**
