### PR TITLE
Revert "Apply damage transformations in GetLayerDamage"

### PR DESCRIPTION
**Pull request by js0701**
Flicker is observed when start an APK after this patch.
for example use Car Launcher

This reverts commit 145bf9c5853cb5b0de0136a076d1a8b9b0b1c8dc.

Conflicts:
	common/core/hwclayer.cpp
	public/hwclayer.h
	public/hwcutils.h

### CODE REVIEW

**Comment by js0701** [comment]
@harishkrupo 
I don't know why
It is better if you can root cause it

**Comment by stripes416** [comment]
@js0701 Can you help me understand why these two commits are in the same PR? They seem to do quite different things and if they don't belong together, we should split them into separate PRs.

**Comment by js0701** [comment]
@stripes416  I agree that should use 2 PRs for those commits
Any easy BKM that 2 PRs can be generated in the same time? Thanks

**Comment by stripes416** [comment]
@js0701 You'll need to split the two commits onto two different branches and do a force push over this one with just commit 2a695dd44441cb475809a3096566ac17dd5ed88f (the one that matches this pr title) and then do a separate pr for commit b2d35e5147d549d827b7e76bb23eeb6c673b85b4.

**Comment by js0701** [comment]
closed this only as the 1st commit merged will generate another one for the second

**Pull request closed without merging**
