### PR TITLE
Fix tests build for Android

### PR DESCRIPTION
**Pull request by XiaosongWei**
Change-Id: Ia3323d3c211d3027f4b765676e2b982b3637c23a
Tracked-On:
Signed-off-by: Xiaosong Wei <xiaosong.wei@intel.com>

### CODE REVIEW

**Comment by XiaosongWei** [comment]
@kalyankondapally

**Comment by kalyankondapally** [comment]
@tpalli ping

**Comment by tpalli** [comment]
this is a partial fix, it fixes some errors but the build itself does not still build executable

**Comment by tpalli** [comment]
it should not try to link or include with libhwcomposer.$(TARGET_BOARD_PLATFORM), there is no such library .. there is libhwcomposer_common and libhwcomposer_wsi

**Comment by tpalli** [comment]
or maybe there is such a library :) I don't really know but most of the functions seem to be at common and wsi libraries

**Comment by kalyankondapally** [comment]
@tpalli this is the static version of hwc which tests link against https://github.com/intel/IA-Hardware-Composer/blob/master/Android.static.mk#L28.     Tests have a dependency on static build of HWC. Since, no other thing depends on the static build, this neither the  tests get built and we end up having to manually build them going into tests folder. This  lines do nothing at this point:

# Include tests only if eng build
ifneq (,$(filter eng,$(TARGET_BUILD_VARIANT)))
include $(HWC_PATH)/tests/third_party/json-c/Android.mk
endif

**Comment by kalyankondapally** [comment]
https://github.com/intel/IA-Hardware-Composer/commit/84a1d4e515f04e6f34f41c84f8bfa75dbf9dd744
https://github.com/intel/IA-Hardware-Composer/commit/22aedaf0fd248ff64005b06e5de30d1c2eb2d66a

These changes plus this one here, I am able to build and run kmscube test atleast. multilayers test segfaults for some reason.

**Comment by kalyankondapally** [comment]
merged

**Pull request closed without merging**
