### PR TITLE
replace spin lock with mutex

### PR DESCRIPTION
**Pull request by dyang23**
The spin lock is a dead-loop waiting lock, incase
a realtime thread waiting for it, the cpu resource
won't be released and trigger a dead-lock, so use
mutext to replace it.

Change-Id: I572effc8fa79df1a1df8bc44c9e70bf86e23acd3
Tracked-On: None
Signed-off-by: zhang jun <jun.zhang@intel.com>
Signed-off-by: Yang, Dong <dong.yang@intel.com>

### CODE REVIEW

**Comment by dyang23** [comment]
Please @Shao-Feng  @YuanjunHuang  help to review

**Comment by tpalli** [comment]
Sometimes spin-lock is better option if we know that the loop will not spin for long time. Mutex has the additional CPU cost and might make the thing slower. It would be good to have perf runs before and after this change to see the effect.

**Comment by dyang23** [comment]
> Sometimes spin-lock is better option if we know that the loop will not spin for long time (or if we call this very often). Mutex has the additional CPU cost and might make the thing slower. It would be good to have perf runs before and after this change to see the effect.

This fix is not from performance perspect, but it's trying fix a deadlock.
On android the display service will run as runtime process, which mean it will never be scheduled out if it's status is runnable. Another thread whose priority is normal and got the spin lock is waiting a mutex, the thread who hold the mutex status is runable, but it run on the same CPU as display service, that is why the deadlock happened.

Usually, spin lock used in kernel, and to protect the race-condition between CPUs rather than process.

**Comment by tpalli** [comment]
@dyang23 Thank you for the detailed explanation, it makes sense. I have no objections for integrating this change, I just wanted to point out the possible perf cost. :)

**Pull request merged**
